db.url=jdbc:db2://localhost:50000/MAXIMO:currentSchema=MAXIMO;
db.username=db2inst1
db.password=Maximo123
db.driver=com.ibm.db2.jcc.DB2Driver

export.output.path=./output/maximo_tables.xlsx
export.object.filter=IBM%
export.object.include=ITEM