server.port: 21001

solon.app:
  name: "maximo-db2-mcp"
  group: "maximo"

#solon.include: app-db.yml
# 引入数据库配置(敏感信息独立管理)
solon.config.load:
  - "app-db.yml"
#  - "app-db-example.yml"


# ===================================================
# MCP 服务配置
# ===================================================
server.http.maxBodySize: 52428800

# 日志级别
solon.logging:
  level:
    root: "info"
    com.maximo: "debug"
# log
solon.logging.appender:
  console:
    level: DEBUG
    enable: true #是否启用
    pattern: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{20} - [%method,%line] \n %msg%n"
  file:
    name: "logs/${solon.app.name}"
    level: DEBUG
    enable: true #是否启用
    extension: ".log"   #v2.2.18 后支持（例：.log, .log.gz, .log.zip）
    maxFileSize: "10 MB"
    maxHistory: "7"
    pattern: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{20} - [%method,%line] - %msg%n"
  cloud:
    level: INFO
    enable: false #是否启用