server.port: 8081

solon.app:
  name: "maximo-db2-mcp"
  group: "maximo"

# 引入数据库配置(敏感信息独立管理)
#solon.include: app-db.yml
solon.include: app-sks.yml

# ===================================================
# MCP 服务配置
# ===================================================
server.http.maxBodySize: 52428800

# 日志级别
solon.logging:
  level:
    root: "info"
    com.maximo: "debug"
